---
- name: "check for mandatory parameter: hostname"
  fail:
    msg: "missing requried parameter: hostname"
  delegate_to: localhost
  with_items: "{{ sys_props }}"
  loop_control:
    loop_var: sys_prop
  when: ( sys_prop.hostname is not defined )

- name: "check for mandatory parameter: domain_name"
  fail:
    msg: "missing requried parameter: domain_name"
  delegate_to: localhost
  with_items: "{{ sys_props }}"
  loop_control:
    loop_var: sys_prop
  when: ( sys_prop.domain_name is not defined )

#- name: "check for maximum supported length of domain name i.e. 13 char"
#  fail:
#    msg: "domain name size is greater than 13 characters"
#  delegate_to: localhost
#  with_items: "{{ sys_props }}"
#  loop_control:
#    loop_var: sys_prop
#  when: sys_prop.domain_name > 13 

- name: "check for junos network connection"
  fail:
    msg: "junos network connection is not netconf"
  delegate_to: localhost
  with_items: "{{ sys_props }}"
  loop_control:
    loop_var: sys_prop
  when: ansible_network_os=="junos" and ansible_connection != "netconf"

- name: "check for mandatory parameter: name_server"
  fail:
    msg: "missing requried parameter: name_server"
  delegate_to: localhost
  with_items: "{{ sys_props }}"
  loop_control:
    loop_var: sys_prop
  when: ( sys_prop.name_server is not defined )

- name: include and run device provider specific tasks  
  include_tasks: main.yml
