---
- name: include role specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - config_sys_prop.yml
      paths:
        - "{{ playbook_dir }}/providers/{{ ansible_network_os }}"
        - "~/.ansible/network/network-vlans/providers/{{ ansible_network_os }}"
        - "/etc/ansible/network/network-vlans/providers/{{ ansible_network_os }}"
        - "{{ role_path }}/providers/{{ ansible_network_os }}"
