---
- name: "iosxr: create hostname, domain and name-server using network_cli connection"
  with_items: "{{ sys_props }}"
  loop_control:
    loop_var: sys_prop
  iosxr_config:
    lines:
      - "hostname {{ sys_prop.hostname }}"
      - "domain name {{ sys_prop.domain_name }}"
      - "domain name-server {{ sys_prop.name_server }}"
      - "domain vrf {{ sys_prop.extensions.iosxr.vrf_name }} name {{ sys_prop.extensions.iosxr.vrf_domain }}"
  connection: network_cli
